services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: dotnet-devcontainer
    volumes:
      - ..:/workspace      
      - ../src/WebApi/appsettings.docker.json:/workspace/src/Migrations/MySqlServer/appsettings.json      
      - ../src/WebApi/appsettings.docker.json:/workspace/src/WebApi/appsettings.json      
      - ../src/WebApi/appsettings.docker.json:/workspace/src/WebApi/appsettings.development.json
      - ../src/AngularApp/src/environments/environment.dev.ts:/workspace/src/AngularApp/src/environments/environment.ts
      - dotnet-nuget:/home/developer/.nuget   # cache de pacotes NuGet
      - aspnet-keys:/home/developer/.aspnet/DataProtection-Keys
      - node_modules:/home/developer/workspace/src/AngularApp/node_modules  # cache de pacotes npm
    working_dir: /workspace/src
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - CONNECTION_STRING=Data Source=/workspace/src/data/app.db
      - TMPDIR=/home/developer/tmp      
    ports:
      - "443:443"   # HTTP
      - "80:80"   # HTTP
      - "42536:42536"   # HTTP http://localhost:42536
      - "42535:42535"   # HTTPS (opcional) http://localhost:42535
      - "4200:4200"   # HTTPS (opcional) http://localhost:42535
    stdin_open: true  # mantém o container vivo
    tty: true
    command: sleep infinity
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    networks:
      - dotnet-network
    depends_on:
      mariadb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    container_name: mariadb
    image: mariadb:10.3.39
    restart: always
    environment:
        TZ: America/Sao_Paulo
        MARIADB_ROOT_PASSWORD: "12345!"
        MARIADB_USER: docker
        MARIADB_PASSWORD: docker
        MARIADB_DATABASE: DespesasPessoaisDB
        LANG: C.UTF-8
    ports:
        - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p12345!"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - dotnet-network      
      
volumes:
  dotnet-nuget:
  aspnet-keys:
  node_modules:

networks:
  dotnet-network:
    driver: bridge
    name: dotnet-network