include:
   - path: ../.docker-infra-db/docker-compose.yml

services:
   app-despesas-pessoais-prod:
      build:
         context: ..
         dockerfile: .docker/Dockerfile.prod
         args:
            - BUILDKIT_INLINE_CACHE=1
      container_name: app-despesas-pessoais-prod
      image: alexfariakof/despesas-backend-prod-img
      environment:
         TZ: America/Sao_Paulo
         ASPNETCORE_ENVIRONMENT: Production
      ports:
         - "80:80"   # HTTP http://localhost
         - "443:443"   # HTTPS (opcional) https://localhost
      volumes:
         - ../src/WebApi/certificate:/app/certificate:ro
      networks:
         - prod-network
         - mariadb-network
      depends_on:
         mariadb:
            condition: service_healthy
      extra_hosts:
            - "host.docker.internal:host-gateway"
      logging:
         driver: json-file
         options:
            max-size: "2m"
            max-file: "1"

networks:
   prod-network:
      driver: bridge
   mariadb-network:
      external: true    

