# ---- Stage 1: Build ----
FROM node:24.16.0-alpine AS build
WORKDIR /app
COPY ./src/AngularApp . 

# Node.js 24.x
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && npm install -g npm@12.0.1 \
    && npm install -g @angular/cli@21.2.13 \
    && npm cache clean --force

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./src/AngularApp/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./src/AngularApp/certificate/ssl_certificate.pem /etc/nginx/certificate/ssl_certificate.pem
COPY ./src/AngularApp/certificate/ssl_certificate.key /etc/nginx/certificate/ssl_certificate.key

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
