services:
  app-despesas-pessoais:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dotnet
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: app-despesas-pessoais
    image: alexfariakof/despesas-backend-img
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "80:80"   # HTTP http://localhost
      - "443:443"   # HTTPS (opcional) https://localhost
    volumes:
      - ../src/WebApi/certificate:/app/certificate:ro
    networks:
      - dotnet-network

networks:
  dotnet-network:
    external: true
    name: dotnet-network